name: ecert
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.14.0-150.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.3.8
  google_fonts: ^2.1.0
  web3dart: ^2.3.1
  shared_preferences: ^2.0.8
  flutter_svg: ^0.23.0+1
  qr_code_scanner: ^0.5.2
  qr_flutter: ^4.0.0
  filepicker_windows: ^2.0.0
  path_provider: ^2.0.5
  archive: ^3.1.6
  cached_network_image: ^3.1.0
  syncfusion_flutter_datagrid: ^19.3.47
  syncfusion_flutter_core: ^19.3.47
  dotted_line: ^3.1.0
  intl: ^0.17.0
  flutter_linkify: ^5.0.2
  url_launcher: ^6.0.12
  excel: ^2.0.0-null-safety-3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  windows: true
  remove_alpha_ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/